# Generated by Django 4.2.2 on 2023-06-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('temperature', models.IntegerField(max_length=6)),
                ('pressure', models.IntegerField(max_length=10)),
                ('humidity', models.IntegerField(max_length=10)),
                ('wind', models.IntegerField(max_length=10)),
                ('main_weather', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
    ]
