# Generated by Django 4.2.2 on 2023-06-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='humidity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='pressure',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temperature',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind',
            field=models.IntegerField(),
        ),
    ]
