# Generated by Django 4.2.2 on 2023-06-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0002_alter_weather_humidity_alter_weather_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='lat',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='weather',
            name='lon',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
