# Generated by Django 4.2.2 on 2023-06-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_weather_lat_weather_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='weather',
            name='lon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
