# Generated by Django 4.2.2 on 2023-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_alter_weather_lat_alter_weather_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='created_at',
            field=models.TimeField(auto_now=True),
        ),
    ]
