# Generated by Django 4.2.2 on 2023-06-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0005_weather_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
