# Generated by Django 4.2.2 on 2023-06-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0006_alter_weather_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
