# Generated by Django 4.2.2 on 2023-06-30 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0007_alter_weather_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
